Added support of Linux platform
MolecularMatters/raw_pdb pull request #11
Opened 2022-04-15 12:14 UTC by FaerHack

I borrowed cmake infra from [stevenhoving:cmake](https://github.com/stevenhoving/raw_pdb/tree/cmake)
Not sure if it can be merged but hope it will be useful for someone

2022-04-29 07:20 UTC, stevenhoving commented
Does this fixes https://github.com/MolecularMatters/raw_pdb/issues/9 ?

2022-04-29 09:56 UTC, MolecularMatters requested changes
Thank you so much for providing Linux support.
I'm terribly sorry that the review took me so long, I somehow completely missed this!

2022-04-29 09:56 UTC, MolecularMatters commented on src/Examples/ExampleContributions.cpp
> +		const size_t countToShow = std::min(static_cast<size_t>(20ul), contributions.size());
I prefer to use std::min<size_t>(arg1, arg2) in this case.

2022-04-29 09:56 UTC, MolecularMatters commented on src/Examples/ExampleFunctionSymbols.cpp
> +#pragma warning (disable : 4189)
Same here.
Please don't disable warnings like this, but fix the issue instead.

2022-04-29 09:56 UTC, MolecularMatters commented on src/Examples/ExampleMemoryMappedFile.cpp
> +		return Handle { INVALID_HANDLE_VALUE, nullptr, 0 };
Doesn't this leak the file handle here?

2022-04-29 09:56 UTC, MolecularMatters commented on src/PDB_ModuleInfoStream.cpp
> +		streamOffset = BitUtil::RoundUpToMultiple(streamOffset, static_cast<size_t>(4ul));
I prefer using an explicit template argument in that case, i.e. BitUtil::RoundUpToMultiple<size_t>(arg1, arg2).

2022-04-29 09:56 UTC, MolecularMatters commented on src/PDB_Types.h
>  	struct GUID
I think a better solution would be to use the uint*_t types here. This is less guesswork for the reader as to how large a struct is, and should make it more compatible with other platforms & compilers.

2022-04-29 19:49 UTC, stevenhoving commented on src/Examples/ExampleFunctionSymbols.cpp
> +#pragma warning (disable : 4189)
indeed

2022-05-03 10:03 UTC, MolecularMatters reviewed
Thanks for fixing most of the issues.
There are only minor things left before this can be merged.

2022-05-03 10:03 UTC, MolecularMatters commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
The library should only need C++11, not 17.

2022-05-03 10:03 UTC, MolecularMatters commented on src/PDB_Types.h
> -}
The GUID definition still needs fixing by switching to the uint*_t types.

2022-05-05 14:19 UTC, MolecularMatters approved these changes
Looks good, thank you again!

2022-05-05 14:19 UTC, merged